name: fastapi를 aws linux에 배포하기

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh 원격 명령
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/hello_fastapi
            
            #프로젝트 경로로 이동 후 git이 설치되어있고 clone 되어있다 가정 하에 pull
            git pull origin master
            
            # python 가상환경 활성화 및 의존성 업데이트
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            
            # 실행중인 프로세스가 있으면 종료
            fuser -k 8000/tcp || true
            
            # 백그라운드로 실행하기
            # nohup으로 실행하고 로그는 app.log에 남기기
            nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &